### ISSUE TITLE
Does not work in python 3.5

### ISSUE THREAD

**Issue by kevinisaac** [milkbikis/powerline-shell#206]
When my system python version is 3.5, I get the error:

```
AttributeError: 'str' object has no attribute 'decode'
```

Works well in python2.7 though.
